server:
  port: 18081
  context-path: /mp-api/ #统一为访问的url加上一个前缀，方便nginx路由，
  compression:
    enabled: true
    mime-types:
      - text/html
      - text/plain
      - text/css
      - application/json
      - application/javascript
#服务监控用
management:
  port: 18089
  security:
    enabled: false
info:
  app:
    name: "@project.name@" #从pom.xml中获取
    description: "@project.description@"
    version: "@project.version@"
    spring-boot-version: "@project.parent.version@"


# 开发环境默认的profile，其他环境需要指定启动参数，比如：java -jar springbootstart.jar --spring.profiles.active=prod
spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
          maxLifetime: 1765000 #一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），缺省:30分钟，建议设置比数据库超时时长少30秒以上
          maximumPoolSize: 15 #连接池中允许的最大连接数。缺省值：10；推荐的公式：((core_count * 2) + effective_spindle_count)

#配置mapper文件扫描目录
mybatis:
  mapperLocations: classpath:mapper/**/*.xml

#微信配置文件
wechat:
  properties:
    appId: 1
    secret: 2
    token: 3
    aesKey: 4

---
# 开发环境配置
spring:
  profiles: dev
  redis:
    #port: 6379
    #host: 192.168.0.10
    cluster:
      nodes:
        - 192.168.0.11:6390
        - 192.168.0.11:6391
        - 192.168.0.11:6392
        - 192.168.0.9:6390
        - 192.168.0.9:6391
        - 192.168.0.9:6392
  datasource:
    url: jdbc:mysql://39.107.244.243:3306
    username: intelhome
    password: home@@123

---
spring:
  profiles: prod
  redis:
    #port: 6379
    #host: 127.0.0.1
    cluster:
      nodes:
        - 127.0.0.1:6390
        - 127.0.0.1:6391
        - 127.0.0.1:6392
        - 127.0.0.1:6393
        - 127.0.0.1:6394
        - 127.0.0.1:6395
  datasource:
    url: jdbc:mysql://39.107.244.243:3306
    username: intelhome
    password: home@@123